### PR TITLE
zketcd: don't crash on getting root directory

### PR DESCRIPTION
**Pull request by heyitsanthony**
/cc @tsuraan

### CODE REVIEW

**Comment by tsuraan** [comment]
Yeah, that works better than mine; the python client actually returns None as the value, which seems more appropriate.

Is rootPath guaranteed to be the only node that behaves this way? Would it be better to check the length of Responses and Kvs to ensure an index out of range panic never happens?

**Comment by heyitsanthony** [comment]
It should only happen for the root node; there are a few special cases for the root node already.

**Comment by tsuraan** [comment]
Okay, cool. I'll close my request.

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
